# Generated by Django 4.2.7 on 2024-01-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('title', models.CharField(blank=True, default=None, help_text='В данном поле задаётся название листа утеплителя, то есть значение. Пример: Текст текст 00мм', max_length=100, null=True, verbose_name='Название')),
                ('sheet_area', models.FloatField(blank=True, default=None, help_text='В данном поле задаётся площадь (м2) листа утеплителя, то есть значение. Пример: 0.00000000000', max_length=100, null=True, verbose_name='Площадь листа (м2)')),
                ('sheet_volume', models.FloatField(blank=True, default=None, help_text='В данном поле задаётся объём (м3) листа утеплителя, то есть значение. Пример: 0.00000000000', max_length=100, null=True, verbose_name='Oбъём листа (м3)')),
                ('sheets_package', models.IntegerField(blank=True, default=None, help_text='В данном поле задаётся объём (м3) листа утеплителя, то есть значение. Пример: 0.00000000000', null=True, verbose_name='Количество листов в упаковке')),
            ],
            options={
                'verbose_name': 'Утеплитель',
                'verbose_name_plural': 'Утеплители',
            },
        ),
    ]
